environmentModel:
  test:
    url: http://automationpractice.com/
    title: Blouses - My Store
    active: N
    webbrowser: FIREFOX

  stag:
    url: http://146.59.32.4/index.php
    title: TesterSii
    active: Y
    webbrowser: CHROME

    # data for failed login test
    emailFailed: wrong@wp.pl
    passwordFailed: passbad999

    #data for successful login test
    emailSuccess: randommail@gmail.com
    passwordSuccess: trudnehas≈Ç@997
